version: "3.9"
services:
       wordpress: 
            image: wordpress
            ports:
              - 8081:80
            volumes:
                - wordpress:/var/www/html    
            environment:
               WORDPRESS_DB_USER: root
               WORDPRESS_DB_PASSWORD: redhat
               WORDPRESS_DB_NAME: sourabh
               WORDPRESS_DB_HOST: database
            depends_on: 
                  - database
       database:
             image: mysql
             volumes: 
                  - database:/var/lib/mysql
             environment:
                 MYSQL_DATABASE: SOURABH
                 MYSQL_ROOT_PASSWORD: REDHAT
volumes: 
                 database:
                 wordpress:  
